# Generated by Django 2.2.5 on 2019-09-27 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20190920_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='backend.ProjectModel', unique=True),
        ),
        migrations.AlterField(
            model_name='teammodel',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leader', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
